package br.com.callink.bradesco.seguro.enums;


/**
 * Representa o nome de Parâmetros de Sistema.
 * 
 * @author swb.thiagohenrique
 * 
 */
public enum ParametroSistemaEnum {
	
	STATUS_PROPOSTA_ATIVOS("LISTA_STATUS_PROPOSTA_ATIVA"),
	STATUS_PROPOSTA_CONCLUIDA("STATUS_PROPOSTA_CONCLUIDA"),
	PARAMETRO_MAX_VL_PROPOSTA("MAX_VL_PROPOSTA"),
	PARAMETRO_PERCENTUAL_FATURAMENTO_MAX_VL_PROPOSTA("PERCENTUAL_FATURAMENTO_MAX_VL_PROPOSTA"),
	PARAMETRO_URL_WSDL_WSPARCELA_TRIBANCO("URL_WSDL_WSPARCELA_TRIBANCO"),
	PARAMETRO_URL_WSDL_WSCLIENT_TRIBANCO("URL_WSDL_WSCLIENT_TRIBANCO"),
	PARAMETRO_SIMULAR_PROPOSTA_FATOR_VENCIMENTO("SIMULAR_PROPOSTA_FATOR_VENCIMENTO"),
	PARAMETRO_SIMULAR_PROPOSTA_INTERVALO("SIMULAR_PROPOSTA_INTERVALO"),
	PARAMETRO_QTD_DIAS_QUARENTENA_EMISSAO_PROPOSTA("QTD_DIAS_QUARENTENA_EMISSAO_PROPOSTA"),
	PARAMETRO_PAPEIS_PERMITIDOS("PAPEIS_PERMITIDOS"),
	PARAMETRO_NOME_LOTE_MAILING_DEFAULT("NOME_LOTE_MAILING_DEFAULT"),
	PARAMETRO_URL_WSDL_WSPROPOSTA_TRIBANCO("URL_WSDL_WSPROPOSTA_TRIBANCO"),
	PARAMETRO_URL_ORIGEM_ARQUIVOS_TRANSFERENCIA("URL_ORIGEM_ARQUIVOS_TRANSFERENCIA"),
	PARAMETRO_URL_DESTINO_ARQUIVOS_TRANSFERENCIA("URL_DESTINO_ARQUIVOS_TRANSFERENCIA"),
	PARAMETRO_CANAL_WSPROPOSTA_TRIBANCO("CANAL_WSPROPOSTA_TRIBANCO"),
	PARAMETRO_SENHA_WSPROPOSTA_TRIBANCO("SENHA_WSPROPOSTA_TRIBANCO"),
	PARAMETRO_ULTIMA_DATA_ENVIO_EVENTO_WSPROPOSTA_TRIBANCO("ULTIMA_DATA_ENVIO_EVENTO_WSPROPOSTA_TRIBANCO"),
	PARAMETRO_ID_EVENTO_FINALIZADOR_LOTE_MAILING("ID_EVENTO_FINALIZADOR_LOTE_MAILING"),
	PARAMETRO_ID_TIPO_CONTATO_ENVIO_EVENTO_WSPROPOSTA_TRIBANCO("ID_TIPO_CONTATO_ENVIO_EVENTO_WSPROPOSTA_TRIBANCO"),
	PARAMETRO_ALM4_STATUS_EXECUCAO_DISPOSITION("ALM4_STATUS_EXECUCAO_DISPOSITION"),
	PARAMETRO_ALM4_DATA_REFERENCIA_SINC_DISPOSITION("ALM4_DATA_REFERENCIA_SINC_DISPOSITION"),
	PARAMETRO_ALM4_TIME_OFFSET_SINC_DISPOSITION("ALM4_TIME_OFFSET_SINC_DISPOSITION"),
	PARAMETRO_ALM4_TIME_DEC_SINC_DISPOSITION("ALM4_TIME_DEC_SINC_DISPOSITION"),
	PARAMETRO_ID_SERVICO_ASPECT("ID_SERVICO_ASPECT"),
	PARAMETRO_CALL_URL_ASPECT("CALL_URL_ASPECT"),
	PARAMETRO_ULTIMA_DATA_ENVIO_PROPOSTAS_EMITIDAS_TRIBANCO("ULTIMA_DATA_ENVIO_PROPOSTAS_EMITIDAS_TRIBANCO"),
	PARAMETRO_CODIGO_OPERACAO_SINCRONIZACAO_USUARIOS_COORPORATIVO("CODIGO_OPERACAO_SINCRONIZACAO_USUARIOS_COORPORATIVO"),
	PARAMETRO_CODIGO_DOMINIOS_SINCRONIZACAO_USUARIOS_COORPORATIVO("CODIGO_DOMINIOS_SINCRONIZACAO_USUARIOS_COORPORATIVO"),
	PARAMETRO_INDICADOR_GERAR_RAW_IMPORTACAO("INDICADOR_GERAR_RAW_IMPORTACAO"),
	PARAMETRO_INDICADOR_GERAR_RAW_MIGRACAO_CARTEIRA("INDICADOR_GERAR_RAW_MIGRACAO_CARTEIRA"),
	PARAMETRO_INDICADOR_GERAR_RAW_INDICACAO_CLIENTE("INDICADOR_GERAR_RAW_INDICACAO_CLIENTE"),
	PARAMETRO_STATUS_PROPOSTA_CONCLUIDA("STATUS_PROPOSTA_CONCLUIDA"),
	PARAMETRO_STATUS_PROPOSTA_ATIVOS("statusPropostaAtivos"),
	PARAMETRO_RETORNO_LIGACAO_ENTRANTE("RETORNO_LIGACAO_ENTRANTE"),
	PARAMETRO_FULL_URL_ARQUIVO_RAW_MIGRACAO("FULL_URL_ARQUIVO_RAW_MIGRACAO"),
	PARAMETRO_ID_LOTE_MAILING_INDICACAO("ID_LOTE_MAILING_INDICACAO"),
	PARAMETRO_ID_CAMPANHA_INDICACAO("ID_CAMPANHA_INDICACAO"),
	PARAMETRO_FULL_URL_ARQUIVO_RAW_INDICACAO("FULL_URL_ARQUIVO_RAW_INDICACAO"),
	PARAMETRO_URL_CUC_TRIBANCO("URL_CUC_TRIBANCO"),
	PARAMETRO_USUARIO_CALLINK_ACESSO_CUC("USUARIO_CALLINK_ACESSO_CUC"),
	PARAMETRO_SENHA_CALLINK_ACESSO_CUC("SENHA_CALLINK_ACESSO_CUC"),
	PARAMETRO_SENHA_CANAL_ACESSO_CUC_TRIBANCO("SENHA_CANAL_ACESSO_CUC_TRIBANCO"),
	PARAMETRO_USUARIO_CANAL_CALLINK_ACESSO_CUC("USUARIO_CANAL_CALLINK_ACESSO_CUC"),
	PARAMETRO_MIN_VL_PROPOSTA("MIN_VL_PROPOSTA"),
	PARAMETRO_CARGOS_LIBERACAO_DE_TAXA_REEMISSAO("CARGOS_LIBERACAO_DE_TAXA_REEMISSAO"),
	URL_CACHE_SERVLET("URL_CACHE_SERVLET"),
	USUARIO_ACESSO_CACHE_SERVLET("USUARIO_ACESSO_CACHE_SERVLET"),
	SENHA_ACESSO_CACHE_SERVLET("SENHA_ACESSO_CACHE_SERVLET")
	;
	
	private String value;

	private ParametroSistemaEnum(String value) {
		this.value = value;
	}

	public String value() {
		return this.value;
	}

	/**
	 * Obtém instancia pelo valor (nome)
	 * 
	 * @param value
	 * @return
	 */
	public ParametroSistemaEnum getInstanceByValue(String value) {
		ParametroSistemaEnum[] parametrosSistema = ParametroSistemaEnum.values();
		for (ParametroSistemaEnum parametroSistema : parametrosSistema) {
			if (parametroSistema.value().equalsIgnoreCase(value)) {
				return parametroSistema;
			}
		}
		return null;
	}
}